language: python
python:
 - "3.7"
 - "3.6"
 - "3.5"
dist: xenial
sudo: yes
install:
 - pip install -r requirements.txt
 - pip install flake8 mypy
script:
 - python -m unittest discover ./tests
 - flake8
 - mypy action --ignore-missing-imports